"""add_projects

Revision ID: e7e07ceaf042
Revises: 428ff63d94e1
Create Date: 2026-04-06 14:43:38.544342
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7e07ceaf042'
down_revision: Union[str, None] = '428ff63d94e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
